version: '3'
services:
  data-aftt-importer:
    build :
      context: ./apps/data-aftt-importer
      dockerfile: Dockerfile
    depends_on:
      - db
      - cache
  tabt-rest:
    build :
      context: ./apps/tabt-rest
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", 'timeout', '10s', 'bash', '-c', ':>', '/dev/tcp/127.0.0.1/3050', '||', 'exit', '1']
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
        - 3050:3050
    depends_on:
      - db
      - cache
      - torproxy
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
      REDIS_HOST: cache
      REDIS_PORT: 6379
      NODE_ENV: prod
      AFTT_WSDL: https://api.aftt.be/?wsdl
      VTLL_WSDL: https://api.aftt.be/?wsdl
      USE_SOCKS_PROXY: false
      PORT: 3050
      SOCKS_PROXY_HOST: torproxy
      SOCKS_PROXY_PORT: 9050
      API_PREFIX: api
      CURRENT_SEASON: 24
      STATIC_PREFIX: static
      HOST: http://localhost:3004
  torproxy:
    image: dockage/tor-privoxy
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
  cache:
    image: redis:6
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - cache-data:/data

volumes:
  db-data:
  cache-data:
