/**
 * TabT Rest
 * This api is a bridge to the TabT SOAP API. It contacts TabT and cache results in order to reduce latency for some requests. More documentation will come.<br>       The data present in the api such as player names, club names, tournaments or match results are not managed by us. This information is made freely available by the Aile Francophone de Tennis de Table and the Vlaamse Tafeltennisliga. We therefore cannot be held responsible for the publication of this information. If changes need to be made, you should contact the responsible entity.     If you build an application on top of the BePing\'s api, be sure to do at least one of the following things:         <ul><li>If possible, set a X-Application-For header string. Include the name of your application, and a way to contact you in case something would go wrong.<br>       An example user agent string format is, which could result in the following string: beping/2.0.0 (floca.be; florent@floca.be). The use of a header like this isn’t obligated or enforced, but allows for better communication.</li></ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: f.cardoen@me.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TournamentSerieEntry } from './tournamentSerieEntry';

export interface TournamentEntry {
  UniqueIndex: number;
  Name: string;
  Level: TournamentEntry.LevelEnum;
  ExternalIndex: string;
  DateFrom: string;
  DateTo: string;
  RegistrationDate: string;
  Venue?: object;
  SerieCount: number;
  SerieEntries: Array<TournamentSerieEntry>;
}
export namespace TournamentEntry {
  export type LevelEnum =
    | 1
    | 4
    | 5
    | 6
    | 7
    | 8
    | 9
    | 10
    | 11
    | 12
    | 13
    | 14
    | 15
    | 16;
  export const LevelEnum = {
    NUMBER_1: 1 as LevelEnum,
    NUMBER_4: 4 as LevelEnum,
    NUMBER_5: 5 as LevelEnum,
    NUMBER_6: 6 as LevelEnum,
    NUMBER_7: 7 as LevelEnum,
    NUMBER_8: 8 as LevelEnum,
    NUMBER_9: 9 as LevelEnum,
    NUMBER_10: 10 as LevelEnum,
    NUMBER_11: 11 as LevelEnum,
    NUMBER_12: 12 as LevelEnum,
    NUMBER_13: 13 as LevelEnum,
    NUMBER_14: 14 as LevelEnum,
    NUMBER_15: 15 as LevelEnum,
    NUMBER_16: 16 as LevelEnum,
  };
}
