name: 'Build and Push Docker Image on Tag Creation'

# push on main
on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 20
  DOCKER_IMAGE_NAME: ghcr.io/fllorent0d/tabt-rest:latest

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        id: docker-build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms:
            - linux/arm64/v8
            - linux/amd64
          file: ./apps/tabt-rest/dockerfile
          tags: ${{ env.DOCKER_IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image to GitHub Container Registry
        run: docker push ${{ env.DOCKER_IMAGE_NAME }}
